import { SimulatedObservableCase } from './latent-engine';

export interface GoldenScenarioFixture {
  id: string;
  name: string;
  description: string;
  expectedAction: string;
  expectedPolicyResult: 'ALLOW' | 'BLOCK' | 'ESCALATE';
  caseData: SimulatedObservableCase;
}

export const GOLDEN_SCENARIOS: GoldenScenarioFixture[] = [
  {
    id: 'golden_01_transient_retry',
    name: 'Transient Gateway Failure',
    description: 'Issuing bank node timeout; transient error where automated RETRY is permitted and high-value.',
    expectedAction: 'RETRY',
    expectedPolicyResult: 'ALLOW',
    caseData: {
      id: 'case_golden_01',
      payment_id: 'pay_golden_01',
      order_id: 'order_golden_01',
      amount: 249900,
      currency: 'INR',
      failure_code: 'GATEWAY_ERROR',
      failure_description: 'Temporary timeout communicating with card issuing network',
      payment_method: 'card',
      customer_context: {
        customer_id: 'cust_g01',
        email: 'priya.sharma@example.com',
        contact: '+919876543210',
        historical_success_rate: 0.95,
        total_prior_transactions: 12,
        prior_failed_transactions: 0,
        lifetime_value: 2998800,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_01',
        outage_type: 'TRANSIENT_GATEWAY',
        customer_intent: 'HIGH',
        alternate_method_available: true,
        time_sensitive: true,
        true_recovery_potential: 0.95,
      },
    },
  },
  {
    id: 'golden_02_payment_link_candidate',
    name: 'Auth Dropout Payment Link Candidate',
    description: '3DS OTP timeout after customer entered card details; optimal recovery is a prefilled payment link.',
    expectedAction: 'CREATE_OR_REUSE_PAYMENT_LINK',
    expectedPolicyResult: 'ALLOW',
    caseData: {
      id: 'case_golden_02',
      payment_id: 'pay_golden_02',
      order_id: 'order_golden_02',
      amount: 450000,
      currency: 'INR',
      failure_code: 'AUTH_TIMEOUT',
      failure_description: 'Customer did not submit OTP before 3DS timeout window elapsed',
      payment_method: 'card',
      customer_context: {
        customer_id: 'cust_g02',
        email: 'rahul.verma@example.com',
        contact: '+919811223344',
        historical_success_rate: 0.88,
        total_prior_transactions: 8,
        prior_failed_transactions: 1,
        lifetime_value: 3600000,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_02',
        outage_type: 'AUTH_DROPOUT',
        customer_intent: 'HIGH',
        alternate_method_available: true,
        time_sensitive: false,
        true_recovery_potential: 0.85,
      },
    },
  },
  {
    id: 'golden_03_hard_decline_blocked_retry',
    name: 'Hard Decline (Expired Card)',
    description: 'Card expired or closed; policy must strictly BLOCK retry on same card and offer alternate method.',
    expectedAction: 'OFFER_ALTERNATE_PAYMENT_METHOD',
    expectedPolicyResult: 'ALLOW',
    caseData: {
      id: 'case_golden_03',
      payment_id: 'pay_golden_03',
      order_id: 'order_golden_03',
      amount: 199900,
      currency: 'INR',
      failure_code: 'EXPIRED_CARD',
      failure_description: 'Card validity date has passed (EXPIRED_CARD)',
      payment_method: 'card',
      customer_context: {
        customer_id: 'cust_g03',
        email: 'ananya.iyer@example.com',
        contact: '+919833445566',
        historical_success_rate: 0.90,
        total_prior_transactions: 10,
        prior_failed_transactions: 1,
        lifetime_value: 1999000,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_03',
        outage_type: 'EXPIRED_INSTRUMENT',
        customer_intent: 'HIGH',
        alternate_method_available: true,
        time_sensitive: false,
        true_recovery_potential: 0.80,
      },
    },
  },
  {
    id: 'golden_04_already_paid_case',
    name: 'Already Paid / Success Verification',
    description: 'Payment was captured out-of-band; system must block further recovery actions.',
    expectedAction: 'STOP',
    expectedPolicyResult: 'ALLOW',
    caseData: {
      id: 'case_golden_04',
      payment_id: 'pay_golden_04',
      order_id: 'order_golden_04',
      amount: 320000,
      currency: 'INR',
      failure_code: 'GATEWAY_ERROR',
      failure_description: 'Prior transient error, but subsequent payment succeeded',
      payment_method: 'upi',
      customer_context: {
        customer_id: 'cust_g04',
        email: 'vikram.singh@example.com',
        contact: '+919844556677',
        historical_success_rate: 1.0,
        total_prior_transactions: 5,
        prior_failed_transactions: 0,
        lifetime_value: 1600000,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_04',
        outage_type: 'TRANSIENT_GATEWAY',
        customer_intent: 'HIGH',
        alternate_method_available: true,
        time_sensitive: false,
        true_recovery_potential: 1.0,
      },
    },
  },
  {
    id: 'golden_05_high_value_escalation',
    name: 'High-Value / Low-Confidence Escalation',
    description: 'Order value of ₹1,20,000 exceeds autonomous limit of ₹50,000; must ESCALATE for human review.',
    expectedAction: 'ESCALATE',
    expectedPolicyResult: 'ESCALATE',
    caseData: {
      id: 'case_golden_05',
      payment_id: 'pay_golden_05',
      order_id: 'order_golden_05',
      amount: 12000000, // 1,20,000 INR
      currency: 'INR',
      failure_code: 'GATEWAY_ERROR',
      failure_description: 'High ticket enterprise order gateway timeout',
      payment_method: 'netbanking',
      customer_context: {
        customer_id: 'cust_g05',
        email: 'procurement@acmecorp.in',
        contact: '+919855667788',
        historical_success_rate: 0.60,
        total_prior_transactions: 2,
        prior_failed_transactions: 1,
        lifetime_value: 24000000,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_05',
        outage_type: 'TRANSIENT_GATEWAY',
        customer_intent: 'MEDIUM',
        alternate_method_available: true,
        time_sensitive: true,
        true_recovery_potential: 0.65,
      },
    },
  },
  {
    id: 'golden_06_unknown_failure_escalation',
    name: 'Unknown Failure Code',
    description: 'Unrecognized error string; system does not hallucinate an action and safely ESCALATES.',
    expectedAction: 'ESCALATE',
    expectedPolicyResult: 'ESCALATE',
    caseData: {
      id: 'case_golden_06',
      payment_id: 'pay_golden_06',
      order_id: 'order_golden_06',
      amount: 150000,
      currency: 'INR',
      failure_code: 'CORRUPTED_INTERNAL_HSM_REJECT_999',
      failure_description: 'Vendor proprietary error code not in standard dictionary',
      payment_method: 'unknown',
      customer_context: {
        customer_id: 'cust_g06',
        email: 'user_06@example.com',
        contact: '+919866778899',
        historical_success_rate: 0.50,
        total_prior_transactions: 2,
        prior_failed_transactions: 1,
        lifetime_value: 300000,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_06',
        outage_type: 'PERSISTENT_OUTAGE',
        customer_intent: 'LOW',
        alternate_method_available: false,
        time_sensitive: false,
        true_recovery_potential: 0.20,
      },
    },
  },
  {
    id: 'golden_07_duplicate_webhook',
    name: 'Duplicate Webhook Delivery',
    description: 'Exact duplicate webhook event is suppressed from re-executing actions while logged in audit.',
    expectedAction: 'RETRY',
    expectedPolicyResult: 'ALLOW',
    caseData: {
      id: 'case_golden_07',
      payment_id: 'pay_golden_07',
      order_id: 'order_golden_07',
      amount: 299900,
      currency: 'INR',
      failure_code: 'GATEWAY_ERROR',
      failure_description: 'Transient network failure',
      payment_method: 'card',
      customer_context: {
        customer_id: 'cust_g07',
        email: 'user_07@example.com',
        contact: '+919877889900',
        historical_success_rate: 0.85,
        total_prior_transactions: 4,
        prior_failed_transactions: 0,
        lifetime_value: 1199600,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_07',
        outage_type: 'TRANSIENT_GATEWAY',
        customer_intent: 'HIGH',
        alternate_method_available: true,
        time_sensitive: false,
        true_recovery_potential: 0.90,
      },
    },
  },
  {
    id: 'golden_08_tool_failure_handling',
    name: 'Controlled Tool Execution Failure',
    description: 'External provider outage during tool call; failure is logged, audited, and not retried forever.',
    expectedAction: 'RETRY',
    expectedPolicyResult: 'ALLOW',
    caseData: {
      id: 'case_golden_08',
      payment_id: 'pay_golden_08',
      order_id: 'order_golden_08',
      amount: 180000,
      currency: 'INR',
      failure_code: 'GATEWAY_ERROR',
      failure_description: 'Transient network failure',
      payment_method: 'card',
      customer_context: {
        customer_id: 'cust_g08',
        email: 'user_08@example.com',
        contact: '+919888990011',
        historical_success_rate: 0.70,
        total_prior_transactions: 3,
        prior_failed_transactions: 1,
        lifetime_value: 540000,
      },
      attempt_count: 1,
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_08',
        outage_type: 'PERSISTENT_OUTAGE',
        customer_intent: 'MEDIUM',
        alternate_method_available: false,
        time_sensitive: false,
        true_recovery_potential: 0.40,
      },
    },
  },
  {
    id: 'golden_09_customer_opt_out',
    name: 'Customer Opt-Out Guardrail',
    description: 'Customer opted out of recovery messages; policy must BLOCK any automated communication.',
    expectedAction: 'CREATE_OR_REUSE_PAYMENT_LINK',
    expectedPolicyResult: 'BLOCK',
    caseData: {
      id: 'case_golden_09',
      payment_id: 'pay_golden_09',
      order_id: 'order_golden_09',
      amount: 220000,
      currency: 'INR',
      failure_code: 'AUTH_TIMEOUT',
      failure_description: 'OTP timed out on customer device',
      payment_method: 'upi',
      customer_context: {
        customer_id: 'cust_g09',
        email: 'optout_user@example.com',
        contact: '+919899001122',
        historical_success_rate: 0.90,
        total_prior_transactions: 6,
        prior_failed_transactions: 0,
        lifetime_value: 1320000,
      },
      attempt_count: 1,
      consent_status: 'OPTED_OUT', // Explicit opt-out
      _hidden_latent: {
        case_id: 'case_golden_09',
        outage_type: 'AUTH_DROPOUT',
        customer_intent: 'CHURNED',
        alternate_method_available: true,
        time_sensitive: false,
        true_recovery_potential: 0.0,
      },
    },
  },
  {
    id: 'golden_10_max_retry_limit',
    name: 'Maximum Retry Limit Exhaustion',
    description: 'Case has already been retried 3 times (configured max); policy blocks further RETRY and STOPs.',
    expectedAction: 'STOP',
    expectedPolicyResult: 'ALLOW',
    caseData: {
      id: 'case_golden_10',
      payment_id: 'pay_golden_10',
      order_id: 'order_golden_10',
      amount: 175000,
      currency: 'INR',
      failure_code: 'GATEWAY_ERROR',
      failure_description: 'Persistent network gateway timeout after repeated attempts',
      payment_method: 'card',
      customer_context: {
        customer_id: 'cust_g10',
        email: 'user_10@example.com',
        contact: '+919800112233',
        historical_success_rate: 0.40,
        total_prior_transactions: 3,
        prior_failed_transactions: 3,
        lifetime_value: 525000,
      },
      attempt_count: 3, // Max retries reached
      consent_status: 'CONSENTED',
      _hidden_latent: {
        case_id: 'case_golden_10',
        outage_type: 'PERSISTENT_OUTAGE',
        customer_intent: 'LOW',
        alternate_method_available: false,
        time_sensitive: false,
        true_recovery_potential: 0.10,
      },
    },
  },
];
